var fs = require('fs');
var path = require('path');

function sync(srcDir, dstDir) {
  fs.rmSync(dstDir, { recursive: true, force: true });
  fs.mkdirSync(dstDir, { recursive: true });
  fs.readdirSync(srcDir).forEach(function (f) {
    if (/\.js$/.test(f)) { fs.copyFileSync(path.join(srcDir, f), path.join(dstDir, f)); }
  });
  fs.writeFileSync(path.join(dstDir, 'README.txt'), 'GENERATED by tools/sync-core.js from /core. Do not edit here.\n');
}

module.exports = { sync: sync };
if (require.main === module) {
  var root = path.join(__dirname, '..');
  sync(path.join(root, 'core'), process.argv[2] || path.join(root, 'shell-enact', 'src', 'core'));
  console.log('core synced');
}
